# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vFirmware_API.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vFirmware_API.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13vFirmware_API.proto\"\x1e\n\x06Vec_2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x88\x01\n\x0bVF_Commands\x12\x0c\n\x04init\x18\x01 \x01(\x08\x12%\n\x14translational_output\x18\x02 \x01(\x0b\x32\x07.Vec_2D\x12\x19\n\x11rotational_output\x18\x03 \x01(\x02\x12\x17\n\x06kicker\x18\x04 \x01(\x0b\x32\x07.Vec_2D\x12\x10\n\x08\x64ribbler\x18\x05 \x01(\x08\"\x9d\x01\n\x07VF_Data\x12+\n\x1atranslational_displacement\x18\x01 \x01(\x0b\x32\x07.Vec_2D\x12\'\n\x16translational_velocity\x18\x02 \x01(\x0b\x32\x07.Vec_2D\x12\x1f\n\x17rotational_displacement\x18\x03 \x01(\x02\x12\x1b\n\x13rotational_velocity\x18\x04 \x01(\x02\x62\x06proto3')
)




_VEC_2D = _descriptor.Descriptor(
  name='Vec_2D',
  full_name='Vec_2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec_2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec_2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=53,
)


_VF_COMMANDS = _descriptor.Descriptor(
  name='VF_Commands',
  full_name='VF_Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='VF_Commands.init', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translational_output', full_name='VF_Commands.translational_output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotational_output', full_name='VF_Commands.rotational_output', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kicker', full_name='VF_Commands.kicker', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler', full_name='VF_Commands.dribbler', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=192,
)


_VF_DATA = _descriptor.Descriptor(
  name='VF_Data',
  full_name='VF_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translational_displacement', full_name='VF_Data.translational_displacement', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translational_velocity', full_name='VF_Data.translational_velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotational_displacement', full_name='VF_Data.rotational_displacement', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotational_velocity', full_name='VF_Data.rotational_velocity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=352,
)

_VF_COMMANDS.fields_by_name['translational_output'].message_type = _VEC_2D
_VF_COMMANDS.fields_by_name['kicker'].message_type = _VEC_2D
_VF_DATA.fields_by_name['translational_displacement'].message_type = _VEC_2D
_VF_DATA.fields_by_name['translational_velocity'].message_type = _VEC_2D
DESCRIPTOR.message_types_by_name['Vec_2D'] = _VEC_2D
DESCRIPTOR.message_types_by_name['VF_Commands'] = _VF_COMMANDS
DESCRIPTOR.message_types_by_name['VF_Data'] = _VF_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vec_2D = _reflection.GeneratedProtocolMessageType('Vec_2D', (_message.Message,), dict(
  DESCRIPTOR = _VEC_2D,
  __module__ = 'vFirmware_API_pb2'
  # @@protoc_insertion_point(class_scope:Vec_2D)
  ))
_sym_db.RegisterMessage(Vec_2D)

VF_Commands = _reflection.GeneratedProtocolMessageType('VF_Commands', (_message.Message,), dict(
  DESCRIPTOR = _VF_COMMANDS,
  __module__ = 'vFirmware_API_pb2'
  # @@protoc_insertion_point(class_scope:VF_Commands)
  ))
_sym_db.RegisterMessage(VF_Commands)

VF_Data = _reflection.GeneratedProtocolMessageType('VF_Data', (_message.Message,), dict(
  DESCRIPTOR = _VF_DATA,
  __module__ = 'vFirmware_API_pb2'
  # @@protoc_insertion_point(class_scope:VF_Data)
  ))
_sym_db.RegisterMessage(VF_Data)


# @@protoc_insertion_point(module_scope)
